---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-data-stream
  name: grpc-data-stream
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: grpc_py_mapping
      grpc: True
      prefix: /datastream.GRPCDataStream/
      rewrite: /datastream.GRPCDataStream/
      service: grpc-data-stream
spec:
  type: ClusterIP
  ports:
  - name: grpc-stream
    port: 80
    targetPort: grpc-api
  selector:
    service: grpc-data-stream
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-data-stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: grpc-data-stream
    spec:
      containers:
      - name: grpc-data-stream
        image: arunramakani/stream-server
        env:
        - name: server
          value: streamblu
        ports:
        - name: grpc-api
          containerPort: 50051
      restartPolicy: Always
